# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('Type', 'Type'), ('DAIRY', 'Dairy'), ('MEAT', 'Meat'), ('VEGETABLE', 'Vegetable')], default='Type', max_length=200)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
